/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUidCounterRouteImport } from './routes/api/uid-counter'
import { Route as ApiEmploymentHistoriesRouteImport } from './routes/api/employment-histories'
import { Route as AuthenticatedWorkHistoryRouteImport } from './routes/_authenticated/work-history'
import { Route as AuthenticatedWorkRouteImport } from './routes/_authenticated/work'
import { Route as AuthenticatedSuperAdminRouteImport } from './routes/_authenticated/super-admin'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedNotebookRouteImport } from './routes/_authenticated/notebook'
import { Route as AuthenticatedNewsRouteImport } from './routes/_authenticated/news'
import { Route as AuthenticatedLastWorkingDayRouteImport } from './routes/_authenticated/last-working-day'
import { Route as AuthenticatedForceChangePasswordRouteImport } from './routes/_authenticated/force-change-password'
import { Route as AuthenticatedExchangeRouteImport } from './routes/_authenticated/exchange'
import { Route as AuthenticatedCounterRouteImport } from './routes/_authenticated/counter'
import { Route as AuthenticatedCheckAttendanceRouteImport } from './routes/_authenticated/check-attendance'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedAdvancesRouteImport } from './routes/_authenticated/advances'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedStaffIndexRouteImport } from './routes/_authenticated/staff.index'
import { Route as ApiWorkforceLookupsRouteImport } from './routes/api/workforce/lookups'
import { Route as ApiWorkforceDashboardRouteImport } from './routes/api/workforce/dashboard'
import { Route as ApiSuperAdminCompaniesRouteImport } from './routes/api/super-admin/companies'
import { Route as ApiStaffExportRouteImport } from './routes/api/staff/export'
import { Route as ApiPushSubscriptionRouteImport } from './routes/api/push/subscription'
import { Route as ApiPushPublicKeyRouteImport } from './routes/api/push/public-key'
import { Route as ApiPushApprovalRouteImport } from './routes/api/push/approval'
import { Route as ApiPublicTenantStatusRouteImport } from './routes/api/public/tenant-status'
import { Route as ApiPublicPocketbaseAuthRouteImport } from './routes/api/public/pocketbase-auth'
import { Route as ApiPublicForceChangePasswordRouteImport } from './routes/api/public/force-change-password'
import { Route as ApiPublicCompanyCodeRouteImport } from './routes/api/public/company-code'
import { Route as ApiPublicAppLogoRouteImport } from './routes/api/public/app-logo'
import { Route as ApiPublicAppIcon512RouteImport } from './routes/api/public/app-icon-512'
import { Route as ApiPublicAppIcon192RouteImport } from './routes/api/public/app-icon-192'
import { Route as ApiPublicAppIconRouteImport } from './routes/api/public/app-icon'
import { Route as ApiEmploymentHistoriesCapacityRouteImport } from './routes/api/employment-histories.capacity'
import { Route as ApiCompanyLoginContextRouteImport } from './routes/api/company/login-context'
import { Route as AuthenticatedStaffWorkforceRouteImport } from './routes/_authenticated/staff.workforce'
import { Route as AuthenticatedStaffToolsRouteImport } from './routes/_authenticated/staff.tools'
import { Route as AuthenticatedStaffSalaryHoldsRouteImport } from './routes/_authenticated/staff.salary-holds'
import { Route as AuthenticatedStaffRecruitedRouteImport } from './routes/_authenticated/staff.recruited'
import { Route as AuthenticatedStaffMoneyToTextRouteImport } from './routes/_authenticated/staff.money-to-text'
import { Route as AuthenticatedStaffHourStatsRouteImport } from './routes/_authenticated/staff.hour-stats'
import { Route as AuthenticatedStaffExportRouteImport } from './routes/_authenticated/staff.export'
import { Route as AuthenticatedStaffApprovalsRouteImport } from './routes/_authenticated/staff.approvals'
import { Route as AuthenticatedStaffAdvancesRouteImport } from './routes/_authenticated/staff.advances'
import { Route as AuthenticatedAdminWorkforceRouteImport } from './routes/_authenticated/admin/workforce'
import { Route as AuthenticatedAdminWorkProgressRouteImport } from './routes/_authenticated/admin/work-progress'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin/staff'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminManageRouteImport } from './routes/_authenticated/admin/manage'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin/logs'
import { Route as AuthenticatedAdminImportsRouteImport } from './routes/_authenticated/admin/imports'
import { Route as AuthenticatedAdminApprovalsRouteImport } from './routes/_authenticated/admin/approvals'
import { Route as AuthenticatedAdminAccountsRouteImport } from './routes/_authenticated/admin/accounts'
import { Route as AuthenticatedStaffWorkersIndexRouteImport } from './routes/_authenticated/staff.workers.index'
import { Route as AuthenticatedStaffToolsIndexRouteImport } from './routes/_authenticated/staff.tools.index'
import { Route as AuthenticatedAdminStaffIndexRouteImport } from './routes/_authenticated/admin/staff.index'
import { Route as AuthenticatedAdminAccountsIndexRouteImport } from './routes/_authenticated/admin/accounts.index'
import { Route as ApiSuperAdminCompaniesCompanyIdRouteImport } from './routes/api/super-admin/companies.$companyId'
import { Route as ApiPublicPbSplatRouteImport } from './routes/api/public/pb.$'
import { Route as ApiPublicManifestWebmanifestRouteImport } from './routes/api/public/manifest.webmanifest'
import { Route as AuthenticatedStaffWorkersWorkerIdRouteImport } from './routes/_authenticated/staff.workers.$workerId'
import { Route as AuthenticatedStaffToolsQrRouteImport } from './routes/_authenticated/staff.tools.qr'
import { Route as AuthenticatedAdminAccountsStatsRouteImport } from './routes/_authenticated/admin/accounts.stats'
import { Route as AuthenticatedAdminAccountsLogsRouteImport } from './routes/_authenticated/admin/accounts.logs'
import { Route as AuthenticatedAdminAccountsFactoriesRouteImport } from './routes/_authenticated/admin/accounts.factories'
import { Route as ApiSuperAdminCompaniesCompanyIdAdminsRouteImport } from './routes/api/super-admin/companies.$companyId.admins'
import { Route as ApiAdminWorkersWorkerIdDeleteRouteImport } from './routes/api/admin/workers.$workerId.delete'
import { Route as AuthenticatedStaffWorkersWorkerIdPayrollRouteImport } from './routes/_authenticated/staff.workers.$workerId_.payroll'
import { Route as ApiSuperAdminCompaniesCompanyIdAdminsAdminIdRouteImport } from './routes/api/super-admin/companies.$companyId.admins.$adminId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUidCounterRoute = ApiUidCounterRouteImport.update({
  id: '/api/uid-counter',
  path: '/api/uid-counter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmploymentHistoriesRoute = ApiEmploymentHistoriesRouteImport.update({
  id: '/api/employment-histories',
  path: '/api/employment-histories',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkHistoryRoute =
  AuthenticatedWorkHistoryRouteImport.update({
    id: '/work-history',
    path: '/work-history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkRoute = AuthenticatedWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuperAdminRoute = AuthenticatedSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotebookRoute = AuthenticatedNotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNewsRoute = AuthenticatedNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLastWorkingDayRoute =
  AuthenticatedLastWorkingDayRouteImport.update({
    id: '/last-working-day',
    path: '/last-working-day',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedForceChangePasswordRoute =
  AuthenticatedForceChangePasswordRouteImport.update({
    id: '/force-change-password',
    path: '/force-change-password',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExchangeRoute = AuthenticatedExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCounterRoute = AuthenticatedCounterRouteImport.update({
  id: '/counter',
  path: '/counter',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCheckAttendanceRoute =
  AuthenticatedCheckAttendanceRouteImport.update({
    id: '/check-attendance',
    path: '/check-attendance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdvancesRoute = AuthenticatedAdvancesRouteImport.update({
  id: '/advances',
  path: '/advances',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedStaffRoute,
} as any)
const ApiWorkforceLookupsRoute = ApiWorkforceLookupsRouteImport.update({
  id: '/api/workforce/lookups',
  path: '/api/workforce/lookups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkforceDashboardRoute = ApiWorkforceDashboardRouteImport.update({
  id: '/api/workforce/dashboard',
  path: '/api/workforce/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSuperAdminCompaniesRoute = ApiSuperAdminCompaniesRouteImport.update({
  id: '/api/super-admin/companies',
  path: '/api/super-admin/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStaffExportRoute = ApiStaffExportRouteImport.update({
  id: '/api/staff/export',
  path: '/api/staff/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushSubscriptionRoute = ApiPushSubscriptionRouteImport.update({
  id: '/api/push/subscription',
  path: '/api/push/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushPublicKeyRoute = ApiPushPublicKeyRouteImport.update({
  id: '/api/push/public-key',
  path: '/api/push/public-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushApprovalRoute = ApiPushApprovalRouteImport.update({
  id: '/api/push/approval',
  path: '/api/push/approval',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTenantStatusRoute = ApiPublicTenantStatusRouteImport.update({
  id: '/api/public/tenant-status',
  path: '/api/public/tenant-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPocketbaseAuthRoute = ApiPublicPocketbaseAuthRouteImport.update({
  id: '/api/public/pocketbase-auth',
  path: '/api/public/pocketbase-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicForceChangePasswordRoute =
  ApiPublicForceChangePasswordRouteImport.update({
    id: '/api/public/force-change-password',
    path: '/api/public/force-change-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCompanyCodeRoute = ApiPublicCompanyCodeRouteImport.update({
  id: '/api/public/company-code',
  path: '/api/public/company-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAppLogoRoute = ApiPublicAppLogoRouteImport.update({
  id: '/api/public/app-logo',
  path: '/api/public/app-logo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAppIcon512Route = ApiPublicAppIcon512RouteImport.update({
  id: '/api/public/app-icon-512',
  path: '/api/public/app-icon-512',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAppIcon192Route = ApiPublicAppIcon192RouteImport.update({
  id: '/api/public/app-icon-192',
  path: '/api/public/app-icon-192',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAppIconRoute = ApiPublicAppIconRouteImport.update({
  id: '/api/public/app-icon',
  path: '/api/public/app-icon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmploymentHistoriesCapacityRoute =
  ApiEmploymentHistoriesCapacityRouteImport.update({
    id: '/capacity',
    path: '/capacity',
    getParentRoute: () => ApiEmploymentHistoriesRoute,
  } as any)
const ApiCompanyLoginContextRoute = ApiCompanyLoginContextRouteImport.update({
  id: '/api/company/login-context',
  path: '/api/company/login-context',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStaffWorkforceRoute =
  AuthenticatedStaffWorkforceRouteImport.update({
    id: '/workforce',
    path: '/workforce',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffToolsRoute = AuthenticatedStaffToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedStaffRoute,
} as any)
const AuthenticatedStaffSalaryHoldsRoute =
  AuthenticatedStaffSalaryHoldsRouteImport.update({
    id: '/salary-holds',
    path: '/salary-holds',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffRecruitedRoute =
  AuthenticatedStaffRecruitedRouteImport.update({
    id: '/recruited',
    path: '/recruited',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffMoneyToTextRoute =
  AuthenticatedStaffMoneyToTextRouteImport.update({
    id: '/money-to-text',
    path: '/money-to-text',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffHourStatsRoute =
  AuthenticatedStaffHourStatsRouteImport.update({
    id: '/hour-stats',
    path: '/hour-stats',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffExportRoute =
  AuthenticatedStaffExportRouteImport.update({
    id: '/export',
    path: '/export',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffApprovalsRoute =
  AuthenticatedStaffApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffAdvancesRoute =
  AuthenticatedStaffAdvancesRouteImport.update({
    id: '/advances',
    path: '/advances',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedAdminWorkforceRoute =
  AuthenticatedAdminWorkforceRouteImport.update({
    id: '/admin/workforce',
    path: '/admin/workforce',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminWorkProgressRoute =
  AuthenticatedAdminWorkProgressRouteImport.update({
    id: '/admin/work-progress',
    path: '/admin/work-progress',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/admin/staff',
  path: '/admin/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminManageRoute =
  AuthenticatedAdminManageRouteImport.update({
    id: '/admin/manage',
    path: '/admin/manage',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminImportsRoute =
  AuthenticatedAdminImportsRouteImport.update({
    id: '/admin/imports',
    path: '/admin/imports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminApprovalsRoute =
  AuthenticatedAdminApprovalsRouteImport.update({
    id: '/admin/approvals',
    path: '/admin/approvals',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAccountsRoute =
  AuthenticatedAdminAccountsRouteImport.update({
    id: '/admin/accounts',
    path: '/admin/accounts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStaffWorkersIndexRoute =
  AuthenticatedStaffWorkersIndexRouteImport.update({
    id: '/workers/',
    path: '/workers/',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffToolsIndexRoute =
  AuthenticatedStaffToolsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStaffToolsRoute,
  } as any)
const AuthenticatedAdminStaffIndexRoute =
  AuthenticatedAdminStaffIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminStaffRoute,
  } as any)
const AuthenticatedAdminAccountsIndexRoute =
  AuthenticatedAdminAccountsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminAccountsRoute,
  } as any)
const ApiSuperAdminCompaniesCompanyIdRoute =
  ApiSuperAdminCompaniesCompanyIdRouteImport.update({
    id: '/$companyId',
    path: '/$companyId',
    getParentRoute: () => ApiSuperAdminCompaniesRoute,
  } as any)
const ApiPublicPbSplatRoute = ApiPublicPbSplatRouteImport.update({
  id: '/api/public/pb/$',
  path: '/api/public/pb/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicManifestWebmanifestRoute =
  ApiPublicManifestWebmanifestRouteImport.update({
    id: '/api/public/manifest/webmanifest',
    path: '/api/public/manifest/webmanifest',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedStaffWorkersWorkerIdRoute =
  AuthenticatedStaffWorkersWorkerIdRouteImport.update({
    id: '/workers/$workerId',
    path: '/workers/$workerId',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffToolsQrRoute =
  AuthenticatedStaffToolsQrRouteImport.update({
    id: '/qr',
    path: '/qr',
    getParentRoute: () => AuthenticatedStaffToolsRoute,
  } as any)
const AuthenticatedAdminAccountsStatsRoute =
  AuthenticatedAdminAccountsStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => AuthenticatedAdminAccountsRoute,
  } as any)
const AuthenticatedAdminAccountsLogsRoute =
  AuthenticatedAdminAccountsLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthenticatedAdminAccountsRoute,
  } as any)
const AuthenticatedAdminAccountsFactoriesRoute =
  AuthenticatedAdminAccountsFactoriesRouteImport.update({
    id: '/factories',
    path: '/factories',
    getParentRoute: () => AuthenticatedAdminAccountsRoute,
  } as any)
const ApiSuperAdminCompaniesCompanyIdAdminsRoute =
  ApiSuperAdminCompaniesCompanyIdAdminsRouteImport.update({
    id: '/admins',
    path: '/admins',
    getParentRoute: () => ApiSuperAdminCompaniesCompanyIdRoute,
  } as any)
const ApiAdminWorkersWorkerIdDeleteRoute =
  ApiAdminWorkersWorkerIdDeleteRouteImport.update({
    id: '/api/admin/workers/$workerId/delete',
    path: '/api/admin/workers/$workerId/delete',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedStaffWorkersWorkerIdPayrollRoute =
  AuthenticatedStaffWorkersWorkerIdPayrollRouteImport.update({
    id: '/workers/$workerId_/payroll',
    path: '/workers/$workerId/payroll',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const ApiSuperAdminCompaniesCompanyIdAdminsAdminIdRoute =
  ApiSuperAdminCompaniesCompanyIdAdminsAdminIdRouteImport.update({
    id: '/$adminId',
    path: '/$adminId',
    getParentRoute: () => ApiSuperAdminCompaniesCompanyIdAdminsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/register': typeof RegisterRoute
  '/account': typeof AuthenticatedAccountRoute
  '/advances': typeof AuthenticatedAdvancesRoute
  '/chat': typeof AuthenticatedChatRoute
  '/check-attendance': typeof AuthenticatedCheckAttendanceRoute
  '/counter': typeof AuthenticatedCounterRoute
  '/exchange': typeof AuthenticatedExchangeRoute
  '/force-change-password': typeof AuthenticatedForceChangePasswordRoute
  '/last-working-day': typeof AuthenticatedLastWorkingDayRoute
  '/news': typeof AuthenticatedNewsRoute
  '/notebook': typeof AuthenticatedNotebookRoute
  '/staff': typeof AuthenticatedStaffRouteWithChildren
  '/super-admin': typeof AuthenticatedSuperAdminRoute
  '/work': typeof AuthenticatedWorkRoute
  '/work-history': typeof AuthenticatedWorkHistoryRoute
  '/api/employment-histories': typeof ApiEmploymentHistoriesRouteWithChildren
  '/api/uid-counter': typeof ApiUidCounterRoute
  '/admin/accounts': typeof AuthenticatedAdminAccountsRouteWithChildren
  '/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/admin/imports': typeof AuthenticatedAdminImportsRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/manage': typeof AuthenticatedAdminManageRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRouteWithChildren
  '/admin/work-progress': typeof AuthenticatedAdminWorkProgressRoute
  '/admin/workforce': typeof AuthenticatedAdminWorkforceRoute
  '/staff/advances': typeof AuthenticatedStaffAdvancesRoute
  '/staff/approvals': typeof AuthenticatedStaffApprovalsRoute
  '/staff/export': typeof AuthenticatedStaffExportRoute
  '/staff/hour-stats': typeof AuthenticatedStaffHourStatsRoute
  '/staff/money-to-text': typeof AuthenticatedStaffMoneyToTextRoute
  '/staff/recruited': typeof AuthenticatedStaffRecruitedRoute
  '/staff/salary-holds': typeof AuthenticatedStaffSalaryHoldsRoute
  '/staff/tools': typeof AuthenticatedStaffToolsRouteWithChildren
  '/staff/workforce': typeof AuthenticatedStaffWorkforceRoute
  '/api/company/login-context': typeof ApiCompanyLoginContextRoute
  '/api/employment-histories/capacity': typeof ApiEmploymentHistoriesCapacityRoute
  '/api/public/app-icon': typeof ApiPublicAppIconRoute
  '/api/public/app-icon-192': typeof ApiPublicAppIcon192Route
  '/api/public/app-icon-512': typeof ApiPublicAppIcon512Route
  '/api/public/app-logo': typeof ApiPublicAppLogoRoute
  '/api/public/company-code': typeof ApiPublicCompanyCodeRoute
  '/api/public/force-change-password': typeof ApiPublicForceChangePasswordRoute
  '/api/public/pocketbase-auth': typeof ApiPublicPocketbaseAuthRoute
  '/api/public/tenant-status': typeof ApiPublicTenantStatusRoute
  '/api/push/approval': typeof ApiPushApprovalRoute
  '/api/push/public-key': typeof ApiPushPublicKeyRoute
  '/api/push/subscription': typeof ApiPushSubscriptionRoute
  '/api/staff/export': typeof ApiStaffExportRoute
  '/api/super-admin/companies': typeof ApiSuperAdminCompaniesRouteWithChildren
  '/api/workforce/dashboard': typeof ApiWorkforceDashboardRoute
  '/api/workforce/lookups': typeof ApiWorkforceLookupsRoute
  '/staff/': typeof AuthenticatedStaffIndexRoute
  '/admin/accounts/factories': typeof AuthenticatedAdminAccountsFactoriesRoute
  '/admin/accounts/logs': typeof AuthenticatedAdminAccountsLogsRoute
  '/admin/accounts/stats': typeof AuthenticatedAdminAccountsStatsRoute
  '/staff/tools/qr': typeof AuthenticatedStaffToolsQrRoute
  '/staff/workers/$workerId': typeof AuthenticatedStaffWorkersWorkerIdRoute
  '/api/public/manifest/webmanifest': typeof ApiPublicManifestWebmanifestRoute
  '/api/public/pb/$': typeof ApiPublicPbSplatRoute
  '/api/super-admin/companies/$companyId': typeof ApiSuperAdminCompaniesCompanyIdRouteWithChildren
  '/admin/accounts/': typeof AuthenticatedAdminAccountsIndexRoute
  '/admin/staff/': typeof AuthenticatedAdminStaffIndexRoute
  '/staff/tools/': typeof AuthenticatedStaffToolsIndexRoute
  '/staff/workers/': typeof AuthenticatedStaffWorkersIndexRoute
  '/staff/workers/$workerId/payroll': typeof AuthenticatedStaffWorkersWorkerIdPayrollRoute
  '/api/admin/workers/$workerId/delete': typeof ApiAdminWorkersWorkerIdDeleteRoute
  '/api/super-admin/companies/$companyId/admins': typeof ApiSuperAdminCompaniesCompanyIdAdminsRouteWithChildren
  '/api/super-admin/companies/$companyId/admins/$adminId': typeof ApiSuperAdminCompaniesCompanyIdAdminsAdminIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/register': typeof RegisterRoute
  '/account': typeof AuthenticatedAccountRoute
  '/advances': typeof AuthenticatedAdvancesRoute
  '/chat': typeof AuthenticatedChatRoute
  '/check-attendance': typeof AuthenticatedCheckAttendanceRoute
  '/counter': typeof AuthenticatedCounterRoute
  '/exchange': typeof AuthenticatedExchangeRoute
  '/force-change-password': typeof AuthenticatedForceChangePasswordRoute
  '/last-working-day': typeof AuthenticatedLastWorkingDayRoute
  '/news': typeof AuthenticatedNewsRoute
  '/notebook': typeof AuthenticatedNotebookRoute
  '/super-admin': typeof AuthenticatedSuperAdminRoute
  '/work': typeof AuthenticatedWorkRoute
  '/work-history': typeof AuthenticatedWorkHistoryRoute
  '/api/employment-histories': typeof ApiEmploymentHistoriesRouteWithChildren
  '/api/uid-counter': typeof ApiUidCounterRoute
  '/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/admin/imports': typeof AuthenticatedAdminImportsRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/manage': typeof AuthenticatedAdminManageRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/work-progress': typeof AuthenticatedAdminWorkProgressRoute
  '/admin/workforce': typeof AuthenticatedAdminWorkforceRoute
  '/staff/advances': typeof AuthenticatedStaffAdvancesRoute
  '/staff/approvals': typeof AuthenticatedStaffApprovalsRoute
  '/staff/export': typeof AuthenticatedStaffExportRoute
  '/staff/hour-stats': typeof AuthenticatedStaffHourStatsRoute
  '/staff/money-to-text': typeof AuthenticatedStaffMoneyToTextRoute
  '/staff/recruited': typeof AuthenticatedStaffRecruitedRoute
  '/staff/salary-holds': typeof AuthenticatedStaffSalaryHoldsRoute
  '/staff/workforce': typeof AuthenticatedStaffWorkforceRoute
  '/api/company/login-context': typeof ApiCompanyLoginContextRoute
  '/api/employment-histories/capacity': typeof ApiEmploymentHistoriesCapacityRoute
  '/api/public/app-icon': typeof ApiPublicAppIconRoute
  '/api/public/app-icon-192': typeof ApiPublicAppIcon192Route
  '/api/public/app-icon-512': typeof ApiPublicAppIcon512Route
  '/api/public/app-logo': typeof ApiPublicAppLogoRoute
  '/api/public/company-code': typeof ApiPublicCompanyCodeRoute
  '/api/public/force-change-password': typeof ApiPublicForceChangePasswordRoute
  '/api/public/pocketbase-auth': typeof ApiPublicPocketbaseAuthRoute
  '/api/public/tenant-status': typeof ApiPublicTenantStatusRoute
  '/api/push/approval': typeof ApiPushApprovalRoute
  '/api/push/public-key': typeof ApiPushPublicKeyRoute
  '/api/push/subscription': typeof ApiPushSubscriptionRoute
  '/api/staff/export': typeof ApiStaffExportRoute
  '/api/super-admin/companies': typeof ApiSuperAdminCompaniesRouteWithChildren
  '/api/workforce/dashboard': typeof ApiWorkforceDashboardRoute
  '/api/workforce/lookups': typeof ApiWorkforceLookupsRoute
  '/staff': typeof AuthenticatedStaffIndexRoute
  '/admin/accounts/factories': typeof AuthenticatedAdminAccountsFactoriesRoute
  '/admin/accounts/logs': typeof AuthenticatedAdminAccountsLogsRoute
  '/admin/accounts/stats': typeof AuthenticatedAdminAccountsStatsRoute
  '/staff/tools/qr': typeof AuthenticatedStaffToolsQrRoute
  '/staff/workers/$workerId': typeof AuthenticatedStaffWorkersWorkerIdRoute
  '/api/public/manifest/webmanifest': typeof ApiPublicManifestWebmanifestRoute
  '/api/public/pb/$': typeof ApiPublicPbSplatRoute
  '/api/super-admin/companies/$companyId': typeof ApiSuperAdminCompaniesCompanyIdRouteWithChildren
  '/admin/accounts': typeof AuthenticatedAdminAccountsIndexRoute
  '/admin/staff': typeof AuthenticatedAdminStaffIndexRoute
  '/staff/tools': typeof AuthenticatedStaffToolsIndexRoute
  '/staff/workers': typeof AuthenticatedStaffWorkersIndexRoute
  '/staff/workers/$workerId/payroll': typeof AuthenticatedStaffWorkersWorkerIdPayrollRoute
  '/api/admin/workers/$workerId/delete': typeof ApiAdminWorkersWorkerIdDeleteRoute
  '/api/super-admin/companies/$companyId/admins': typeof ApiSuperAdminCompaniesCompanyIdAdminsRouteWithChildren
  '/api/super-admin/companies/$companyId/admins/$adminId': typeof ApiSuperAdminCompaniesCompanyIdAdminsAdminIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/register': typeof RegisterRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/advances': typeof AuthenticatedAdvancesRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/check-attendance': typeof AuthenticatedCheckAttendanceRoute
  '/_authenticated/counter': typeof AuthenticatedCounterRoute
  '/_authenticated/exchange': typeof AuthenticatedExchangeRoute
  '/_authenticated/force-change-password': typeof AuthenticatedForceChangePasswordRoute
  '/_authenticated/last-working-day': typeof AuthenticatedLastWorkingDayRoute
  '/_authenticated/news': typeof AuthenticatedNewsRoute
  '/_authenticated/notebook': typeof AuthenticatedNotebookRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRouteWithChildren
  '/_authenticated/super-admin': typeof AuthenticatedSuperAdminRoute
  '/_authenticated/work': typeof AuthenticatedWorkRoute
  '/_authenticated/work-history': typeof AuthenticatedWorkHistoryRoute
  '/api/employment-histories': typeof ApiEmploymentHistoriesRouteWithChildren
  '/api/uid-counter': typeof ApiUidCounterRoute
  '/_authenticated/admin/accounts': typeof AuthenticatedAdminAccountsRouteWithChildren
  '/_authenticated/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/_authenticated/admin/imports': typeof AuthenticatedAdminImportsRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/manage': typeof AuthenticatedAdminManageRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRouteWithChildren
  '/_authenticated/admin/work-progress': typeof AuthenticatedAdminWorkProgressRoute
  '/_authenticated/admin/workforce': typeof AuthenticatedAdminWorkforceRoute
  '/_authenticated/staff/advances': typeof AuthenticatedStaffAdvancesRoute
  '/_authenticated/staff/approvals': typeof AuthenticatedStaffApprovalsRoute
  '/_authenticated/staff/export': typeof AuthenticatedStaffExportRoute
  '/_authenticated/staff/hour-stats': typeof AuthenticatedStaffHourStatsRoute
  '/_authenticated/staff/money-to-text': typeof AuthenticatedStaffMoneyToTextRoute
  '/_authenticated/staff/recruited': typeof AuthenticatedStaffRecruitedRoute
  '/_authenticated/staff/salary-holds': typeof AuthenticatedStaffSalaryHoldsRoute
  '/_authenticated/staff/tools': typeof AuthenticatedStaffToolsRouteWithChildren
  '/_authenticated/staff/workforce': typeof AuthenticatedStaffWorkforceRoute
  '/api/company/login-context': typeof ApiCompanyLoginContextRoute
  '/api/employment-histories/capacity': typeof ApiEmploymentHistoriesCapacityRoute
  '/api/public/app-icon': typeof ApiPublicAppIconRoute
  '/api/public/app-icon-192': typeof ApiPublicAppIcon192Route
  '/api/public/app-icon-512': typeof ApiPublicAppIcon512Route
  '/api/public/app-logo': typeof ApiPublicAppLogoRoute
  '/api/public/company-code': typeof ApiPublicCompanyCodeRoute
  '/api/public/force-change-password': typeof ApiPublicForceChangePasswordRoute
  '/api/public/pocketbase-auth': typeof ApiPublicPocketbaseAuthRoute
  '/api/public/tenant-status': typeof ApiPublicTenantStatusRoute
  '/api/push/approval': typeof ApiPushApprovalRoute
  '/api/push/public-key': typeof ApiPushPublicKeyRoute
  '/api/push/subscription': typeof ApiPushSubscriptionRoute
  '/api/staff/export': typeof ApiStaffExportRoute
  '/api/super-admin/companies': typeof ApiSuperAdminCompaniesRouteWithChildren
  '/api/workforce/dashboard': typeof ApiWorkforceDashboardRoute
  '/api/workforce/lookups': typeof ApiWorkforceLookupsRoute
  '/_authenticated/staff/': typeof AuthenticatedStaffIndexRoute
  '/_authenticated/admin/accounts/factories': typeof AuthenticatedAdminAccountsFactoriesRoute
  '/_authenticated/admin/accounts/logs': typeof AuthenticatedAdminAccountsLogsRoute
  '/_authenticated/admin/accounts/stats': typeof AuthenticatedAdminAccountsStatsRoute
  '/_authenticated/staff/tools/qr': typeof AuthenticatedStaffToolsQrRoute
  '/_authenticated/staff/workers/$workerId': typeof AuthenticatedStaffWorkersWorkerIdRoute
  '/api/public/manifest/webmanifest': typeof ApiPublicManifestWebmanifestRoute
  '/api/public/pb/$': typeof ApiPublicPbSplatRoute
  '/api/super-admin/companies/$companyId': typeof ApiSuperAdminCompaniesCompanyIdRouteWithChildren
  '/_authenticated/admin/accounts/': typeof AuthenticatedAdminAccountsIndexRoute
  '/_authenticated/admin/staff/': typeof AuthenticatedAdminStaffIndexRoute
  '/_authenticated/staff/tools/': typeof AuthenticatedStaffToolsIndexRoute
  '/_authenticated/staff/workers/': typeof AuthenticatedStaffWorkersIndexRoute
  '/_authenticated/staff/workers/$workerId_/payroll': typeof AuthenticatedStaffWorkersWorkerIdPayrollRoute
  '/api/admin/workers/$workerId/delete': typeof ApiAdminWorkersWorkerIdDeleteRoute
  '/api/super-admin/companies/$companyId/admins': typeof ApiSuperAdminCompaniesCompanyIdAdminsRouteWithChildren
  '/api/super-admin/companies/$companyId/admins/$adminId': typeof ApiSuperAdminCompaniesCompanyIdAdminsAdminIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/pending'
    | '/register'
    | '/account'
    | '/advances'
    | '/chat'
    | '/check-attendance'
    | '/counter'
    | '/exchange'
    | '/force-change-password'
    | '/last-working-day'
    | '/news'
    | '/notebook'
    | '/staff'
    | '/super-admin'
    | '/work'
    | '/work-history'
    | '/api/employment-histories'
    | '/api/uid-counter'
    | '/admin/accounts'
    | '/admin/approvals'
    | '/admin/imports'
    | '/admin/logs'
    | '/admin/manage'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/work-progress'
    | '/admin/workforce'
    | '/staff/advances'
    | '/staff/approvals'
    | '/staff/export'
    | '/staff/hour-stats'
    | '/staff/money-to-text'
    | '/staff/recruited'
    | '/staff/salary-holds'
    | '/staff/tools'
    | '/staff/workforce'
    | '/api/company/login-context'
    | '/api/employment-histories/capacity'
    | '/api/public/app-icon'
    | '/api/public/app-icon-192'
    | '/api/public/app-icon-512'
    | '/api/public/app-logo'
    | '/api/public/company-code'
    | '/api/public/force-change-password'
    | '/api/public/pocketbase-auth'
    | '/api/public/tenant-status'
    | '/api/push/approval'
    | '/api/push/public-key'
    | '/api/push/subscription'
    | '/api/staff/export'
    | '/api/super-admin/companies'
    | '/api/workforce/dashboard'
    | '/api/workforce/lookups'
    | '/staff/'
    | '/admin/accounts/factories'
    | '/admin/accounts/logs'
    | '/admin/accounts/stats'
    | '/staff/tools/qr'
    | '/staff/workers/$workerId'
    | '/api/public/manifest/webmanifest'
    | '/api/public/pb/$'
    | '/api/super-admin/companies/$companyId'
    | '/admin/accounts/'
    | '/admin/staff/'
    | '/staff/tools/'
    | '/staff/workers/'
    | '/staff/workers/$workerId/payroll'
    | '/api/admin/workers/$workerId/delete'
    | '/api/super-admin/companies/$companyId/admins'
    | '/api/super-admin/companies/$companyId/admins/$adminId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/pending'
    | '/register'
    | '/account'
    | '/advances'
    | '/chat'
    | '/check-attendance'
    | '/counter'
    | '/exchange'
    | '/force-change-password'
    | '/last-working-day'
    | '/news'
    | '/notebook'
    | '/super-admin'
    | '/work'
    | '/work-history'
    | '/api/employment-histories'
    | '/api/uid-counter'
    | '/admin/approvals'
    | '/admin/imports'
    | '/admin/logs'
    | '/admin/manage'
    | '/admin/settings'
    | '/admin/work-progress'
    | '/admin/workforce'
    | '/staff/advances'
    | '/staff/approvals'
    | '/staff/export'
    | '/staff/hour-stats'
    | '/staff/money-to-text'
    | '/staff/recruited'
    | '/staff/salary-holds'
    | '/staff/workforce'
    | '/api/company/login-context'
    | '/api/employment-histories/capacity'
    | '/api/public/app-icon'
    | '/api/public/app-icon-192'
    | '/api/public/app-icon-512'
    | '/api/public/app-logo'
    | '/api/public/company-code'
    | '/api/public/force-change-password'
    | '/api/public/pocketbase-auth'
    | '/api/public/tenant-status'
    | '/api/push/approval'
    | '/api/push/public-key'
    | '/api/push/subscription'
    | '/api/staff/export'
    | '/api/super-admin/companies'
    | '/api/workforce/dashboard'
    | '/api/workforce/lookups'
    | '/staff'
    | '/admin/accounts/factories'
    | '/admin/accounts/logs'
    | '/admin/accounts/stats'
    | '/staff/tools/qr'
    | '/staff/workers/$workerId'
    | '/api/public/manifest/webmanifest'
    | '/api/public/pb/$'
    | '/api/super-admin/companies/$companyId'
    | '/admin/accounts'
    | '/admin/staff'
    | '/staff/tools'
    | '/staff/workers'
    | '/staff/workers/$workerId/payroll'
    | '/api/admin/workers/$workerId/delete'
    | '/api/super-admin/companies/$companyId/admins'
    | '/api/super-admin/companies/$companyId/admins/$adminId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/login'
    | '/pending'
    | '/register'
    | '/_authenticated/account'
    | '/_authenticated/advances'
    | '/_authenticated/chat'
    | '/_authenticated/check-attendance'
    | '/_authenticated/counter'
    | '/_authenticated/exchange'
    | '/_authenticated/force-change-password'
    | '/_authenticated/last-working-day'
    | '/_authenticated/news'
    | '/_authenticated/notebook'
    | '/_authenticated/staff'
    | '/_authenticated/super-admin'
    | '/_authenticated/work'
    | '/_authenticated/work-history'
    | '/api/employment-histories'
    | '/api/uid-counter'
    | '/_authenticated/admin/accounts'
    | '/_authenticated/admin/approvals'
    | '/_authenticated/admin/imports'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/manage'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/staff'
    | '/_authenticated/admin/work-progress'
    | '/_authenticated/admin/workforce'
    | '/_authenticated/staff/advances'
    | '/_authenticated/staff/approvals'
    | '/_authenticated/staff/export'
    | '/_authenticated/staff/hour-stats'
    | '/_authenticated/staff/money-to-text'
    | '/_authenticated/staff/recruited'
    | '/_authenticated/staff/salary-holds'
    | '/_authenticated/staff/tools'
    | '/_authenticated/staff/workforce'
    | '/api/company/login-context'
    | '/api/employment-histories/capacity'
    | '/api/public/app-icon'
    | '/api/public/app-icon-192'
    | '/api/public/app-icon-512'
    | '/api/public/app-logo'
    | '/api/public/company-code'
    | '/api/public/force-change-password'
    | '/api/public/pocketbase-auth'
    | '/api/public/tenant-status'
    | '/api/push/approval'
    | '/api/push/public-key'
    | '/api/push/subscription'
    | '/api/staff/export'
    | '/api/super-admin/companies'
    | '/api/workforce/dashboard'
    | '/api/workforce/lookups'
    | '/_authenticated/staff/'
    | '/_authenticated/admin/accounts/factories'
    | '/_authenticated/admin/accounts/logs'
    | '/_authenticated/admin/accounts/stats'
    | '/_authenticated/staff/tools/qr'
    | '/_authenticated/staff/workers/$workerId'
    | '/api/public/manifest/webmanifest'
    | '/api/public/pb/$'
    | '/api/super-admin/companies/$companyId'
    | '/_authenticated/admin/accounts/'
    | '/_authenticated/admin/staff/'
    | '/_authenticated/staff/tools/'
    | '/_authenticated/staff/workers/'
    | '/_authenticated/staff/workers/$workerId_/payroll'
    | '/api/admin/workers/$workerId/delete'
    | '/api/super-admin/companies/$companyId/admins'
    | '/api/super-admin/companies/$companyId/admins/$adminId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  PendingRoute: typeof PendingRoute
  RegisterRoute: typeof RegisterRoute
  ApiEmploymentHistoriesRoute: typeof ApiEmploymentHistoriesRouteWithChildren
  ApiUidCounterRoute: typeof ApiUidCounterRoute
  ApiCompanyLoginContextRoute: typeof ApiCompanyLoginContextRoute
  ApiPublicAppIconRoute: typeof ApiPublicAppIconRoute
  ApiPublicAppIcon192Route: typeof ApiPublicAppIcon192Route
  ApiPublicAppIcon512Route: typeof ApiPublicAppIcon512Route
  ApiPublicAppLogoRoute: typeof ApiPublicAppLogoRoute
  ApiPublicCompanyCodeRoute: typeof ApiPublicCompanyCodeRoute
  ApiPublicForceChangePasswordRoute: typeof ApiPublicForceChangePasswordRoute
  ApiPublicPocketbaseAuthRoute: typeof ApiPublicPocketbaseAuthRoute
  ApiPublicTenantStatusRoute: typeof ApiPublicTenantStatusRoute
  ApiPushApprovalRoute: typeof ApiPushApprovalRoute
  ApiPushPublicKeyRoute: typeof ApiPushPublicKeyRoute
  ApiPushSubscriptionRoute: typeof ApiPushSubscriptionRoute
  ApiStaffExportRoute: typeof ApiStaffExportRoute
  ApiSuperAdminCompaniesRoute: typeof ApiSuperAdminCompaniesRouteWithChildren
  ApiWorkforceDashboardRoute: typeof ApiWorkforceDashboardRoute
  ApiWorkforceLookupsRoute: typeof ApiWorkforceLookupsRoute
  ApiPublicManifestWebmanifestRoute: typeof ApiPublicManifestWebmanifestRoute
  ApiPublicPbSplatRoute: typeof ApiPublicPbSplatRoute
  ApiAdminWorkersWorkerIdDeleteRoute: typeof ApiAdminWorkersWorkerIdDeleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uid-counter': {
      id: '/api/uid-counter'
      path: '/api/uid-counter'
      fullPath: '/api/uid-counter'
      preLoaderRoute: typeof ApiUidCounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/employment-histories': {
      id: '/api/employment-histories'
      path: '/api/employment-histories'
      fullPath: '/api/employment-histories'
      preLoaderRoute: typeof ApiEmploymentHistoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/work-history': {
      id: '/_authenticated/work-history'
      path: '/work-history'
      fullPath: '/work-history'
      preLoaderRoute: typeof AuthenticatedWorkHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/work': {
      id: '/_authenticated/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof AuthenticatedWorkRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin': {
      id: '/_authenticated/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AuthenticatedSuperAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notebook': {
      id: '/_authenticated/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof AuthenticatedNotebookRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/news': {
      id: '/_authenticated/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AuthenticatedNewsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/last-working-day': {
      id: '/_authenticated/last-working-day'
      path: '/last-working-day'
      fullPath: '/last-working-day'
      preLoaderRoute: typeof AuthenticatedLastWorkingDayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/force-change-password': {
      id: '/_authenticated/force-change-password'
      path: '/force-change-password'
      fullPath: '/force-change-password'
      preLoaderRoute: typeof AuthenticatedForceChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exchange': {
      id: '/_authenticated/exchange'
      path: '/exchange'
      fullPath: '/exchange'
      preLoaderRoute: typeof AuthenticatedExchangeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/counter': {
      id: '/_authenticated/counter'
      path: '/counter'
      fullPath: '/counter'
      preLoaderRoute: typeof AuthenticatedCounterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/check-attendance': {
      id: '/_authenticated/check-attendance'
      path: '/check-attendance'
      fullPath: '/check-attendance'
      preLoaderRoute: typeof AuthenticatedCheckAttendanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/advances': {
      id: '/_authenticated/advances'
      path: '/advances'
      fullPath: '/advances'
      preLoaderRoute: typeof AuthenticatedAdvancesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff/': {
      id: '/_authenticated/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/api/workforce/lookups': {
      id: '/api/workforce/lookups'
      path: '/api/workforce/lookups'
      fullPath: '/api/workforce/lookups'
      preLoaderRoute: typeof ApiWorkforceLookupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workforce/dashboard': {
      id: '/api/workforce/dashboard'
      path: '/api/workforce/dashboard'
      fullPath: '/api/workforce/dashboard'
      preLoaderRoute: typeof ApiWorkforceDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/super-admin/companies': {
      id: '/api/super-admin/companies'
      path: '/api/super-admin/companies'
      fullPath: '/api/super-admin/companies'
      preLoaderRoute: typeof ApiSuperAdminCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/staff/export': {
      id: '/api/staff/export'
      path: '/api/staff/export'
      fullPath: '/api/staff/export'
      preLoaderRoute: typeof ApiStaffExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/subscription': {
      id: '/api/push/subscription'
      path: '/api/push/subscription'
      fullPath: '/api/push/subscription'
      preLoaderRoute: typeof ApiPushSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/public-key': {
      id: '/api/push/public-key'
      path: '/api/push/public-key'
      fullPath: '/api/push/public-key'
      preLoaderRoute: typeof ApiPushPublicKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/approval': {
      id: '/api/push/approval'
      path: '/api/push/approval'
      fullPath: '/api/push/approval'
      preLoaderRoute: typeof ApiPushApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tenant-status': {
      id: '/api/public/tenant-status'
      path: '/api/public/tenant-status'
      fullPath: '/api/public/tenant-status'
      preLoaderRoute: typeof ApiPublicTenantStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pocketbase-auth': {
      id: '/api/public/pocketbase-auth'
      path: '/api/public/pocketbase-auth'
      fullPath: '/api/public/pocketbase-auth'
      preLoaderRoute: typeof ApiPublicPocketbaseAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/force-change-password': {
      id: '/api/public/force-change-password'
      path: '/api/public/force-change-password'
      fullPath: '/api/public/force-change-password'
      preLoaderRoute: typeof ApiPublicForceChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/company-code': {
      id: '/api/public/company-code'
      path: '/api/public/company-code'
      fullPath: '/api/public/company-code'
      preLoaderRoute: typeof ApiPublicCompanyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/app-logo': {
      id: '/api/public/app-logo'
      path: '/api/public/app-logo'
      fullPath: '/api/public/app-logo'
      preLoaderRoute: typeof ApiPublicAppLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/app-icon-512': {
      id: '/api/public/app-icon-512'
      path: '/api/public/app-icon-512'
      fullPath: '/api/public/app-icon-512'
      preLoaderRoute: typeof ApiPublicAppIcon512RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/app-icon-192': {
      id: '/api/public/app-icon-192'
      path: '/api/public/app-icon-192'
      fullPath: '/api/public/app-icon-192'
      preLoaderRoute: typeof ApiPublicAppIcon192RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/app-icon': {
      id: '/api/public/app-icon'
      path: '/api/public/app-icon'
      fullPath: '/api/public/app-icon'
      preLoaderRoute: typeof ApiPublicAppIconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/employment-histories/capacity': {
      id: '/api/employment-histories/capacity'
      path: '/capacity'
      fullPath: '/api/employment-histories/capacity'
      preLoaderRoute: typeof ApiEmploymentHistoriesCapacityRouteImport
      parentRoute: typeof ApiEmploymentHistoriesRoute
    }
    '/api/company/login-context': {
      id: '/api/company/login-context'
      path: '/api/company/login-context'
      fullPath: '/api/company/login-context'
      preLoaderRoute: typeof ApiCompanyLoginContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/staff/workforce': {
      id: '/_authenticated/staff/workforce'
      path: '/workforce'
      fullPath: '/staff/workforce'
      preLoaderRoute: typeof AuthenticatedStaffWorkforceRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/tools': {
      id: '/_authenticated/staff/tools'
      path: '/tools'
      fullPath: '/staff/tools'
      preLoaderRoute: typeof AuthenticatedStaffToolsRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/salary-holds': {
      id: '/_authenticated/staff/salary-holds'
      path: '/salary-holds'
      fullPath: '/staff/salary-holds'
      preLoaderRoute: typeof AuthenticatedStaffSalaryHoldsRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/recruited': {
      id: '/_authenticated/staff/recruited'
      path: '/recruited'
      fullPath: '/staff/recruited'
      preLoaderRoute: typeof AuthenticatedStaffRecruitedRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/money-to-text': {
      id: '/_authenticated/staff/money-to-text'
      path: '/money-to-text'
      fullPath: '/staff/money-to-text'
      preLoaderRoute: typeof AuthenticatedStaffMoneyToTextRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/hour-stats': {
      id: '/_authenticated/staff/hour-stats'
      path: '/hour-stats'
      fullPath: '/staff/hour-stats'
      preLoaderRoute: typeof AuthenticatedStaffHourStatsRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/export': {
      id: '/_authenticated/staff/export'
      path: '/export'
      fullPath: '/staff/export'
      preLoaderRoute: typeof AuthenticatedStaffExportRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/approvals': {
      id: '/_authenticated/staff/approvals'
      path: '/approvals'
      fullPath: '/staff/approvals'
      preLoaderRoute: typeof AuthenticatedStaffApprovalsRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/advances': {
      id: '/_authenticated/staff/advances'
      path: '/advances'
      fullPath: '/staff/advances'
      preLoaderRoute: typeof AuthenticatedStaffAdvancesRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/admin/workforce': {
      id: '/_authenticated/admin/workforce'
      path: '/admin/workforce'
      fullPath: '/admin/workforce'
      preLoaderRoute: typeof AuthenticatedAdminWorkforceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/work-progress': {
      id: '/_authenticated/admin/work-progress'
      path: '/admin/work-progress'
      fullPath: '/admin/work-progress'
      preLoaderRoute: typeof AuthenticatedAdminWorkProgressRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/admin/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/manage': {
      id: '/_authenticated/admin/manage'
      path: '/admin/manage'
      fullPath: '/admin/manage'
      preLoaderRoute: typeof AuthenticatedAdminManageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/imports': {
      id: '/_authenticated/admin/imports'
      path: '/admin/imports'
      fullPath: '/admin/imports'
      preLoaderRoute: typeof AuthenticatedAdminImportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/approvals': {
      id: '/_authenticated/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AuthenticatedAdminApprovalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/accounts': {
      id: '/_authenticated/admin/accounts'
      path: '/admin/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AuthenticatedAdminAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff/workers/': {
      id: '/_authenticated/staff/workers/'
      path: '/workers'
      fullPath: '/staff/workers/'
      preLoaderRoute: typeof AuthenticatedStaffWorkersIndexRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/tools/': {
      id: '/_authenticated/staff/tools/'
      path: '/'
      fullPath: '/staff/tools/'
      preLoaderRoute: typeof AuthenticatedStaffToolsIndexRouteImport
      parentRoute: typeof AuthenticatedStaffToolsRoute
    }
    '/_authenticated/admin/staff/': {
      id: '/_authenticated/admin/staff/'
      path: '/'
      fullPath: '/admin/staff/'
      preLoaderRoute: typeof AuthenticatedAdminStaffIndexRouteImport
      parentRoute: typeof AuthenticatedAdminStaffRoute
    }
    '/_authenticated/admin/accounts/': {
      id: '/_authenticated/admin/accounts/'
      path: '/'
      fullPath: '/admin/accounts/'
      preLoaderRoute: typeof AuthenticatedAdminAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminAccountsRoute
    }
    '/api/super-admin/companies/$companyId': {
      id: '/api/super-admin/companies/$companyId'
      path: '/$companyId'
      fullPath: '/api/super-admin/companies/$companyId'
      preLoaderRoute: typeof ApiSuperAdminCompaniesCompanyIdRouteImport
      parentRoute: typeof ApiSuperAdminCompaniesRoute
    }
    '/api/public/pb/$': {
      id: '/api/public/pb/$'
      path: '/api/public/pb/$'
      fullPath: '/api/public/pb/$'
      preLoaderRoute: typeof ApiPublicPbSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/manifest/webmanifest': {
      id: '/api/public/manifest/webmanifest'
      path: '/api/public/manifest/webmanifest'
      fullPath: '/api/public/manifest/webmanifest'
      preLoaderRoute: typeof ApiPublicManifestWebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/staff/workers/$workerId': {
      id: '/_authenticated/staff/workers/$workerId'
      path: '/workers/$workerId'
      fullPath: '/staff/workers/$workerId'
      preLoaderRoute: typeof AuthenticatedStaffWorkersWorkerIdRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/tools/qr': {
      id: '/_authenticated/staff/tools/qr'
      path: '/qr'
      fullPath: '/staff/tools/qr'
      preLoaderRoute: typeof AuthenticatedStaffToolsQrRouteImport
      parentRoute: typeof AuthenticatedStaffToolsRoute
    }
    '/_authenticated/admin/accounts/stats': {
      id: '/_authenticated/admin/accounts/stats'
      path: '/stats'
      fullPath: '/admin/accounts/stats'
      preLoaderRoute: typeof AuthenticatedAdminAccountsStatsRouteImport
      parentRoute: typeof AuthenticatedAdminAccountsRoute
    }
    '/_authenticated/admin/accounts/logs': {
      id: '/_authenticated/admin/accounts/logs'
      path: '/logs'
      fullPath: '/admin/accounts/logs'
      preLoaderRoute: typeof AuthenticatedAdminAccountsLogsRouteImport
      parentRoute: typeof AuthenticatedAdminAccountsRoute
    }
    '/_authenticated/admin/accounts/factories': {
      id: '/_authenticated/admin/accounts/factories'
      path: '/factories'
      fullPath: '/admin/accounts/factories'
      preLoaderRoute: typeof AuthenticatedAdminAccountsFactoriesRouteImport
      parentRoute: typeof AuthenticatedAdminAccountsRoute
    }
    '/api/super-admin/companies/$companyId/admins': {
      id: '/api/super-admin/companies/$companyId/admins'
      path: '/admins'
      fullPath: '/api/super-admin/companies/$companyId/admins'
      preLoaderRoute: typeof ApiSuperAdminCompaniesCompanyIdAdminsRouteImport
      parentRoute: typeof ApiSuperAdminCompaniesCompanyIdRoute
    }
    '/api/admin/workers/$workerId/delete': {
      id: '/api/admin/workers/$workerId/delete'
      path: '/api/admin/workers/$workerId/delete'
      fullPath: '/api/admin/workers/$workerId/delete'
      preLoaderRoute: typeof ApiAdminWorkersWorkerIdDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/staff/workers/$workerId_/payroll': {
      id: '/_authenticated/staff/workers/$workerId_/payroll'
      path: '/workers/$workerId/payroll'
      fullPath: '/staff/workers/$workerId/payroll'
      preLoaderRoute: typeof AuthenticatedStaffWorkersWorkerIdPayrollRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/api/super-admin/companies/$companyId/admins/$adminId': {
      id: '/api/super-admin/companies/$companyId/admins/$adminId'
      path: '/$adminId'
      fullPath: '/api/super-admin/companies/$companyId/admins/$adminId'
      preLoaderRoute: typeof ApiSuperAdminCompaniesCompanyIdAdminsAdminIdRouteImport
      parentRoute: typeof ApiSuperAdminCompaniesCompanyIdAdminsRoute
    }
  }
}

interface AuthenticatedStaffToolsRouteChildren {
  AuthenticatedStaffToolsQrRoute: typeof AuthenticatedStaffToolsQrRoute
  AuthenticatedStaffToolsIndexRoute: typeof AuthenticatedStaffToolsIndexRoute
}

const AuthenticatedStaffToolsRouteChildren: AuthenticatedStaffToolsRouteChildren =
  {
    AuthenticatedStaffToolsQrRoute: AuthenticatedStaffToolsQrRoute,
    AuthenticatedStaffToolsIndexRoute: AuthenticatedStaffToolsIndexRoute,
  }

const AuthenticatedStaffToolsRouteWithChildren =
  AuthenticatedStaffToolsRoute._addFileChildren(
    AuthenticatedStaffToolsRouteChildren,
  )

interface AuthenticatedStaffRouteChildren {
  AuthenticatedStaffAdvancesRoute: typeof AuthenticatedStaffAdvancesRoute
  AuthenticatedStaffApprovalsRoute: typeof AuthenticatedStaffApprovalsRoute
  AuthenticatedStaffExportRoute: typeof AuthenticatedStaffExportRoute
  AuthenticatedStaffHourStatsRoute: typeof AuthenticatedStaffHourStatsRoute
  AuthenticatedStaffMoneyToTextRoute: typeof AuthenticatedStaffMoneyToTextRoute
  AuthenticatedStaffRecruitedRoute: typeof AuthenticatedStaffRecruitedRoute
  AuthenticatedStaffSalaryHoldsRoute: typeof AuthenticatedStaffSalaryHoldsRoute
  AuthenticatedStaffToolsRoute: typeof AuthenticatedStaffToolsRouteWithChildren
  AuthenticatedStaffWorkforceRoute: typeof AuthenticatedStaffWorkforceRoute
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute
  AuthenticatedStaffWorkersWorkerIdRoute: typeof AuthenticatedStaffWorkersWorkerIdRoute
  AuthenticatedStaffWorkersIndexRoute: typeof AuthenticatedStaffWorkersIndexRoute
  AuthenticatedStaffWorkersWorkerIdPayrollRoute: typeof AuthenticatedStaffWorkersWorkerIdPayrollRoute
}

const AuthenticatedStaffRouteChildren: AuthenticatedStaffRouteChildren = {
  AuthenticatedStaffAdvancesRoute: AuthenticatedStaffAdvancesRoute,
  AuthenticatedStaffApprovalsRoute: AuthenticatedStaffApprovalsRoute,
  AuthenticatedStaffExportRoute: AuthenticatedStaffExportRoute,
  AuthenticatedStaffHourStatsRoute: AuthenticatedStaffHourStatsRoute,
  AuthenticatedStaffMoneyToTextRoute: AuthenticatedStaffMoneyToTextRoute,
  AuthenticatedStaffRecruitedRoute: AuthenticatedStaffRecruitedRoute,
  AuthenticatedStaffSalaryHoldsRoute: AuthenticatedStaffSalaryHoldsRoute,
  AuthenticatedStaffToolsRoute: AuthenticatedStaffToolsRouteWithChildren,
  AuthenticatedStaffWorkforceRoute: AuthenticatedStaffWorkforceRoute,
  AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute,
  AuthenticatedStaffWorkersWorkerIdRoute:
    AuthenticatedStaffWorkersWorkerIdRoute,
  AuthenticatedStaffWorkersIndexRoute: AuthenticatedStaffWorkersIndexRoute,
  AuthenticatedStaffWorkersWorkerIdPayrollRoute:
    AuthenticatedStaffWorkersWorkerIdPayrollRoute,
}

const AuthenticatedStaffRouteWithChildren =
  AuthenticatedStaffRoute._addFileChildren(AuthenticatedStaffRouteChildren)

interface AuthenticatedAdminAccountsRouteChildren {
  AuthenticatedAdminAccountsFactoriesRoute: typeof AuthenticatedAdminAccountsFactoriesRoute
  AuthenticatedAdminAccountsLogsRoute: typeof AuthenticatedAdminAccountsLogsRoute
  AuthenticatedAdminAccountsStatsRoute: typeof AuthenticatedAdminAccountsStatsRoute
  AuthenticatedAdminAccountsIndexRoute: typeof AuthenticatedAdminAccountsIndexRoute
}

const AuthenticatedAdminAccountsRouteChildren: AuthenticatedAdminAccountsRouteChildren =
  {
    AuthenticatedAdminAccountsFactoriesRoute:
      AuthenticatedAdminAccountsFactoriesRoute,
    AuthenticatedAdminAccountsLogsRoute: AuthenticatedAdminAccountsLogsRoute,
    AuthenticatedAdminAccountsStatsRoute: AuthenticatedAdminAccountsStatsRoute,
    AuthenticatedAdminAccountsIndexRoute: AuthenticatedAdminAccountsIndexRoute,
  }

const AuthenticatedAdminAccountsRouteWithChildren =
  AuthenticatedAdminAccountsRoute._addFileChildren(
    AuthenticatedAdminAccountsRouteChildren,
  )

interface AuthenticatedAdminStaffRouteChildren {
  AuthenticatedAdminStaffIndexRoute: typeof AuthenticatedAdminStaffIndexRoute
}

const AuthenticatedAdminStaffRouteChildren: AuthenticatedAdminStaffRouteChildren =
  {
    AuthenticatedAdminStaffIndexRoute: AuthenticatedAdminStaffIndexRoute,
  }

const AuthenticatedAdminStaffRouteWithChildren =
  AuthenticatedAdminStaffRoute._addFileChildren(
    AuthenticatedAdminStaffRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdvancesRoute: typeof AuthenticatedAdvancesRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedCheckAttendanceRoute: typeof AuthenticatedCheckAttendanceRoute
  AuthenticatedCounterRoute: typeof AuthenticatedCounterRoute
  AuthenticatedExchangeRoute: typeof AuthenticatedExchangeRoute
  AuthenticatedForceChangePasswordRoute: typeof AuthenticatedForceChangePasswordRoute
  AuthenticatedLastWorkingDayRoute: typeof AuthenticatedLastWorkingDayRoute
  AuthenticatedNewsRoute: typeof AuthenticatedNewsRoute
  AuthenticatedNotebookRoute: typeof AuthenticatedNotebookRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRouteWithChildren
  AuthenticatedSuperAdminRoute: typeof AuthenticatedSuperAdminRoute
  AuthenticatedWorkRoute: typeof AuthenticatedWorkRoute
  AuthenticatedWorkHistoryRoute: typeof AuthenticatedWorkHistoryRoute
  AuthenticatedAdminAccountsRoute: typeof AuthenticatedAdminAccountsRouteWithChildren
  AuthenticatedAdminApprovalsRoute: typeof AuthenticatedAdminApprovalsRoute
  AuthenticatedAdminImportsRoute: typeof AuthenticatedAdminImportsRoute
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminManageRoute: typeof AuthenticatedAdminManageRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRouteWithChildren
  AuthenticatedAdminWorkProgressRoute: typeof AuthenticatedAdminWorkProgressRoute
  AuthenticatedAdminWorkforceRoute: typeof AuthenticatedAdminWorkforceRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdvancesRoute: AuthenticatedAdvancesRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedCheckAttendanceRoute: AuthenticatedCheckAttendanceRoute,
  AuthenticatedCounterRoute: AuthenticatedCounterRoute,
  AuthenticatedExchangeRoute: AuthenticatedExchangeRoute,
  AuthenticatedForceChangePasswordRoute: AuthenticatedForceChangePasswordRoute,
  AuthenticatedLastWorkingDayRoute: AuthenticatedLastWorkingDayRoute,
  AuthenticatedNewsRoute: AuthenticatedNewsRoute,
  AuthenticatedNotebookRoute: AuthenticatedNotebookRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRouteWithChildren,
  AuthenticatedSuperAdminRoute: AuthenticatedSuperAdminRoute,
  AuthenticatedWorkRoute: AuthenticatedWorkRoute,
  AuthenticatedWorkHistoryRoute: AuthenticatedWorkHistoryRoute,
  AuthenticatedAdminAccountsRoute: AuthenticatedAdminAccountsRouteWithChildren,
  AuthenticatedAdminApprovalsRoute: AuthenticatedAdminApprovalsRoute,
  AuthenticatedAdminImportsRoute: AuthenticatedAdminImportsRoute,
  AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
  AuthenticatedAdminManageRoute: AuthenticatedAdminManageRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRouteWithChildren,
  AuthenticatedAdminWorkProgressRoute: AuthenticatedAdminWorkProgressRoute,
  AuthenticatedAdminWorkforceRoute: AuthenticatedAdminWorkforceRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiEmploymentHistoriesRouteChildren {
  ApiEmploymentHistoriesCapacityRoute: typeof ApiEmploymentHistoriesCapacityRoute
}

const ApiEmploymentHistoriesRouteChildren: ApiEmploymentHistoriesRouteChildren =
  {
    ApiEmploymentHistoriesCapacityRoute: ApiEmploymentHistoriesCapacityRoute,
  }

const ApiEmploymentHistoriesRouteWithChildren =
  ApiEmploymentHistoriesRoute._addFileChildren(
    ApiEmploymentHistoriesRouteChildren,
  )

interface ApiSuperAdminCompaniesCompanyIdAdminsRouteChildren {
  ApiSuperAdminCompaniesCompanyIdAdminsAdminIdRoute: typeof ApiSuperAdminCompaniesCompanyIdAdminsAdminIdRoute
}

const ApiSuperAdminCompaniesCompanyIdAdminsRouteChildren: ApiSuperAdminCompaniesCompanyIdAdminsRouteChildren =
  {
    ApiSuperAdminCompaniesCompanyIdAdminsAdminIdRoute:
      ApiSuperAdminCompaniesCompanyIdAdminsAdminIdRoute,
  }

const ApiSuperAdminCompaniesCompanyIdAdminsRouteWithChildren =
  ApiSuperAdminCompaniesCompanyIdAdminsRoute._addFileChildren(
    ApiSuperAdminCompaniesCompanyIdAdminsRouteChildren,
  )

interface ApiSuperAdminCompaniesCompanyIdRouteChildren {
  ApiSuperAdminCompaniesCompanyIdAdminsRoute: typeof ApiSuperAdminCompaniesCompanyIdAdminsRouteWithChildren
}

const ApiSuperAdminCompaniesCompanyIdRouteChildren: ApiSuperAdminCompaniesCompanyIdRouteChildren =
  {
    ApiSuperAdminCompaniesCompanyIdAdminsRoute:
      ApiSuperAdminCompaniesCompanyIdAdminsRouteWithChildren,
  }

const ApiSuperAdminCompaniesCompanyIdRouteWithChildren =
  ApiSuperAdminCompaniesCompanyIdRoute._addFileChildren(
    ApiSuperAdminCompaniesCompanyIdRouteChildren,
  )

interface ApiSuperAdminCompaniesRouteChildren {
  ApiSuperAdminCompaniesCompanyIdRoute: typeof ApiSuperAdminCompaniesCompanyIdRouteWithChildren
}

const ApiSuperAdminCompaniesRouteChildren: ApiSuperAdminCompaniesRouteChildren =
  {
    ApiSuperAdminCompaniesCompanyIdRoute:
      ApiSuperAdminCompaniesCompanyIdRouteWithChildren,
  }

const ApiSuperAdminCompaniesRouteWithChildren =
  ApiSuperAdminCompaniesRoute._addFileChildren(
    ApiSuperAdminCompaniesRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  PendingRoute: PendingRoute,
  RegisterRoute: RegisterRoute,
  ApiEmploymentHistoriesRoute: ApiEmploymentHistoriesRouteWithChildren,
  ApiUidCounterRoute: ApiUidCounterRoute,
  ApiCompanyLoginContextRoute: ApiCompanyLoginContextRoute,
  ApiPublicAppIconRoute: ApiPublicAppIconRoute,
  ApiPublicAppIcon192Route: ApiPublicAppIcon192Route,
  ApiPublicAppIcon512Route: ApiPublicAppIcon512Route,
  ApiPublicAppLogoRoute: ApiPublicAppLogoRoute,
  ApiPublicCompanyCodeRoute: ApiPublicCompanyCodeRoute,
  ApiPublicForceChangePasswordRoute: ApiPublicForceChangePasswordRoute,
  ApiPublicPocketbaseAuthRoute: ApiPublicPocketbaseAuthRoute,
  ApiPublicTenantStatusRoute: ApiPublicTenantStatusRoute,
  ApiPushApprovalRoute: ApiPushApprovalRoute,
  ApiPushPublicKeyRoute: ApiPushPublicKeyRoute,
  ApiPushSubscriptionRoute: ApiPushSubscriptionRoute,
  ApiStaffExportRoute: ApiStaffExportRoute,
  ApiSuperAdminCompaniesRoute: ApiSuperAdminCompaniesRouteWithChildren,
  ApiWorkforceDashboardRoute: ApiWorkforceDashboardRoute,
  ApiWorkforceLookupsRoute: ApiWorkforceLookupsRoute,
  ApiPublicManifestWebmanifestRoute: ApiPublicManifestWebmanifestRoute,
  ApiPublicPbSplatRoute: ApiPublicPbSplatRoute,
  ApiAdminWorkersWorkerIdDeleteRoute: ApiAdminWorkersWorkerIdDeleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
